[book]
authors = ["Gytis Ivaskevicius"]
language = "en"
multilingual = false
src = "src"
title = "nix-toolbox"

[output.html.search]
enable = false
[output.json.search]
enable = false
[output.json]
optional = true
