jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v3
    - name: 🧰 Setup Nix
      uses: nixbuild/nix-quick-install-action@v28
    - name: Start k8s cluster
      run: nix run .#createK8sCluster
    - name: 🚀 Deploy
      uses: ./ci/helm
      with:
        action: ${{inputs.action}}
        deploymentAttrPath: helm.examples.nginx
        target: ${{inputs.target}}
        targetsToDiff: dev,prod
name: nginx-example
'on':
  pull_request: null
  workflow_call:
    inputs:
      action:
        type: string
      target:
        type: string
      targetsToDiff:
        type: string
  workflow_dispatch:
    inputs:
      action:
        description: Action
        options:
        - apply
        - destroy
        - plan
        required: true
        type: choice
      target:
        description: Targets
        options:
        - dev
        - prod
        required: true
        type: choice
permissions:
  contents: read
  pull-requests: write
